# Generated by Django 5.2.12 on 2026-04-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
