# Generated by Django 5.2.12 on 2026-04-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_goal_current_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='current_amount',
        ),
    ]
