# Generated by Django 5.2.12 on 2026-05-04 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('csvhandler', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFile',
        ),
    ]
